version: "3"

tasks:
  build:
    desc: build CNI plugin
    cmds:
      - CGO_ENABLED=0 go build -o ./bin/make-net .

  create-cluster:
    cmds:
      - task build
      - kind create cluster --config kind.yaml
      - kubectl apply -f https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset.yml
      - docker cp ./bin/make-net kind-control-plane:/opt/cni/bin
      - docker cp ./bin/make-net kind-worker:/opt/cni/bin
      - kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=5m

  deploy:
    cmds:
      - kubectl apply -f ./files/netdef.yaml
      - kubectl create configmap frr-daemons --from-file=./files/daemons
      - kubectl apply -f ./files/frr.yaml
    
  delete-cluster:
    cmds:
      - kind delete cluster
